#!/bin/bash
#PBS -N reprotest
#PBS -A P28100045
#PBS -q develop
#PBS -l select=1:ncpus=64:ompthreads=64
#PBS -l walltime=00:40:00
#PBS -j oe
#PBS -o /glade/work/yizhu/cuspML/reproduce/run.log
source /glade/u/home/yizhu/work/miniconda3/etc/profile.d/conda.sh
conda activate py3.10
cd /glade/work/yizhu/cuspML/reproduce
export CUSPML_NJOBS=32
echo "START $(date) on $(hostname)"
python reproduce.py
echo "REPRODONE $(date)"
